# -*- coding: utf-8 -*-
"""EV_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T-6KScvfkSfn1p5IW35UPcdLIGpFsRBI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(style="whitegrid")

df = pd.read_csv("C:\EV_Project\last_ev_dataset_realistic.csv")

print(df.head())
print(df.columns)

df.info()
df.describe()

df = df.dropna()

df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Start_Time'], errors='coerce')

df = df.dropna(subset=['Datetime'])

df['Hour'] = df['Datetime'].dt.hour

df['Battery_Category'] = pd.cut(df['Battery_%'],
                               bins=[0, 20, 50, 80, 100],
                               labels=["Low", "Medium", "High", "Full"])

df['Waiting_Category'] = pd.cut(df['Waiting_Time'],
                               bins=[0, 10, 30, 60, 200],
                               labels=["Low", "Medium", "High", "Very High"])

plt.figure()
df['Station_Name'].value_counts().plot(kind='bar')
plt.title("Station Usage")
plt.xticks(rotation=45)
plt.show()

plt.figure()
sns.countplot(x='Hour', data=df)
plt.title("Peak Usage Hours")
plt.show()

plt.figure()
sns.boxplot(x='Station_Name', y='Waiting_Time', data=df)
plt.xticks(rotation=45)
plt.title("Waiting Time by Station")
plt.show()

plt.figure()
sns.scatterplot(x='Distance_km', y='Waiting_Time', data=df)
plt.title("Distance vs Waiting Time")
plt.show()

plt.figure()
df['Connector_Type'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Connector Type Distribution")
plt.ylabel("")
plt.show()

plt.figure()
sns.histplot(df['Battery_%'], bins=20)
plt.title("Battery Level Distribution")
plt.show()

plt.figure()
sns.barplot(x='Station_Name', y='Rating', data=df)
plt.xticks(rotation=45)
plt.title("Station Ratings")
plt.show()

plt.figure()
sns.barplot(x='Station_Name', y='Queue_Length', data=df)
plt.xticks(rotation=45)
plt.title("Queue Length by Station")
plt.show()

summary = df.groupby('Station_Name').agg({
    'Waiting_Time': 'mean',
    'Distance_km': 'mean',
    'Rating': 'mean',
    'Queue_Length': 'mean'
}).reset_index()
print(summary)

summary['Score'] = (
    (1 / summary['Distance_km']) * 0.4 +
    (1 / summary['Waiting_Time']) * 0.3 +
    (summary['Rating']) * 0.3
)
print(summary.sort_values(by='Score', ascending=False))

plt.figure()
sns.heatmap(df.corr(numeric_only=True), annot=True)
plt.title("Correlation Heatmap")
plt.show()

df['Day'] = df['Datetime'].dt.day_name()
sns.countplot(x='Day', data=df)
plt.title("Usage by Day")
plt.xticks(rotation=45)
plt.show()

summary.sort_values(by='Score', ascending=False).head()

df.groupby('Location')['Energy_Consumed_kWh'].mean()

df.groupby('Connector_Type').agg({
    'Energy_Consumed_kWh': 'mean',
    'Connector_Type': 'count'
})

sns.histplot(df['Queue_Length'], bins=10)
plt.title("Queue Length Distribution")
plt.show()

sns.barplot(x='Queue_Length', y='Energy_Consumed_kWh', data=df)
plt.title("Energy vs Queue Length")
plt.show()



import folium

# Create base map (centered around Chennai)
m = folium.Map(location=[13.0827, 80.2707], zoom_start=11)

# Function to assign color based on queue
def get_color(queue):
    if queue <= 2:
        return 'green'
    elif queue <= 5:
        return 'orange'
    else:
        return 'red'

# Add points to map
for i, row in df.iterrows():
    folium.CircleMarker(
        location=[row['Latitude'], row['Longitude']],
        radius=6,
        color=get_color(row['Queue_Length']),
        fill=True,
        fill_color=get_color(row['Queue_Length']),
        fill_opacity=0.7,
        popup=f"""
        Station: {row['Station_Name']}<br>
        Location: {row['Location']}<br>
        Queue: {row['Queue_Length']}<br>
        Energy: {row['Energy_Consumed_kWh']} kWh<br>
        Slots: {row['Slots']}<br>
        Vehicles: {row['Vehicles_Count']}
        """
    ).add_to(m)

# Show map
m.save("ev_map.html")

plt.figure(figsize=(8,6))
sns.scatterplot(x='Longitude', y='Latitude', hue='Station_Name', data=df)
plt.title("Station Map View")
plt.show()

